const types = {
	UPDATE_FIELD_VALUE_AUTH:
		'UPDATE_FIELD_VALUE_AUTH',

	AUTH_ATTEMPT_SIGNIN:
		'AUTH_ATTEMPT_SIGNIN',
	AUTH_ATTEMPT_SIGNIN_FULFILLED:
		'AUTH_ATTEMPT_SIGNIN_FULFILLED',
	AUTH_ATTEMPT_SIGNIN_ERROR:
		'AUTH_ATTEMPT_SIGNIN_ERROR',

	AUTH_ATTEMPT_REGISTER:
		'AUTH_ATTEMPT_REGISTER',
	AUTH_ATTEMPT_REGISTER_FULFILLED:
		'AUTH_ATTEMPT_REGISTER_FULFILLED',
	AUTH_ATTEMPT_REGISTER_ERROR:
		'AUTH_ATTEMPT_REGISTER_ERROR',

	FETCH_JUNCTURES:
		'FETCH_JUNCTURES',
	FETCH_JUNCTURES_PENDING:
		'FETCH_JUNCTURES_PENDING',
	FETCH_JUNCTURES_FULFILLED:
		'FETCH_JUNCTURES_FULFILLED'
};

export default types;
