const types = {
	GOTO:
		'GOTO',
	REDIRECTED:
		'REDIRECTED',

	AUTH_UPDATE_FIELD_VALUE:
		'AUTH_UPDATE_FIELD_VALUE',

	AUTH_ATTEMPT_SIGNIN:
		'AUTH_ATTEMPT_SIGNIN',
	AUTH_ATTEMPT_SIGNIN_FULFILLED:
		'AUTH_ATTEMPT_SIGNIN_FULFILLED',
	AUTH_ATTEMPT_SIGNIN_ERROR:
		'AUTH_ATTEMPT_SIGNIN_ERROR',

	AUTH_ATTEMPT_REGISTER:
		'AUTH_ATTEMPT_REGISTER',
	AUTH_ATTEMPT_REGISTER_FULFILLED:
		'AUTH_ATTEMPT_REGISTER_FULFILLED',
	AUTH_ATTEMPT_REGISTER_ERROR:
		'AUTH_ATTEMPT_REGISTER_ERROR',

	AUTH_SIGN_OUT:
		'AUTH_SIGN_OUT',
	AUTH_SIGN_OUT_FULFILLED:
		'AUTH_SIGN_OUT_FULFILLED',
	AUTH_SIGN_OUT_FAILED:
		'AUTH_SIGN_OUT_FAILED',

	AUTH_UNLOAD:
		'AUTH_UNLOAD',

	USER_AUTHENTICATED:
		'USER_AUTHENTICATED',
	USER_NOT_AUTHENTICATED:
		'USER_NOT_AUTHENTICATED',

	JUNCTURE_UPDATE_FIELD:
		'JUNCTURE_UPDATE_FIELD',
	JUNCTURE_UPDATE_UNLOAD:
		'JUNCTURE_UPDATE_UNLOAD',

	JUNCTURE_CREATE:
		'JUNCTURE_CREATE',
	JUNCTURE_CREATE_FULFILLED:
		'JUNCTURE_CREATE_FULFILLED',
	JUNCTURE_CREATE_ERROR:
		'JUNCTURE_CREATE_ERROR',

	JUNCTURE_FETCH_BY_ID:
		'JUNCTURE_FETCH_BY_ID',
	JUNCTURE_FETCH_BY_ID_FULFILLED:
		'JUNCTURE_FETCH_BY_ID_FULFILLED',
	JUNCTURE_FETCH_BY_ID_ERROR:
		'JUNCTURE_FETCH_BY_ID_ERROR',

	JUNCTURE_EDIT:
		'JUNCTURE_EDIT',
	JUNCTURE_EDIT_FULFILLED:
		'JUNCTURE_EDIT_FULFILLED',
	JUNCTURE_EDIT_ERROR:
		'JUNCTURE_EDIT_ERROR',

	JUNCTURE_DELETE:
		'JUNCTURE_DELETE',
	JUNCTURE_DELETE_FULFILLED:
		'JUNCTURE_DELETE_FULFILLED',
	JUNCTURE_DELETE_ERROR:
		'JUNCTURE_DELETE_ERROR',

	JUNCTURES_LIST_WATCH:
		'JUNCTURES_LIST_WATCH',
	JUNCTURES_LIST_CHILD_ADDED:
		'JUNCTURES_LIST_CHILD_ADDED',
	JUNCTURES_LIST_CHILD_CHANGED:
		'JUNCTURES_LIST_CHILD_CHANGED',
	JUNCTURES_LIST_CHILD_REMOVED:
		'JUNCTURES_LIST_CHILD_REMOVED',
	JUNCTURES_LIST_UNWATCH:
		'JUNCTURES_LIST_UNWATCH',
};

export default types;
